# -*- coding: utf-8 -*-
"""Negation Handeling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Hy6B1aEoRA3c_R3FXz2nbbpNAgN7cOvt
"""

import pandas as pd

# Read the Excel file into a DataFrame
df = pd.read_csv('/content/negation.csv')
df_tweet = pd.read_csv('/content/data.csv')

# Create the dictionary of negation sentences and alternatives
negation_dict = df.set_index('negation')['alternative'].to_dict()


for i in range(len(df_tweet)):
  df_tweet['tweet'][i] = df_tweet['tweet'][i].lower()

print(df_tweet)

# Replace the negation sentences with their alternatives
for negation, alternative in negation_dict.items():
  for i in range(len(df_tweet)):
    df_tweet['tweet'][i] = df_tweet['tweet'][i].replace(negation, alternative)

print(df_tweet)  # Output: modified text with negation sentences replaced